version: '3'
services:
  nginx:
    image: nginx:1.15
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./src/magento:/var/www/magento
    depends_on:
      - php-fpm
  php-fpm:
    build: ./docker/php-fpm
    restart: always
    volumes:
      - ./src/magento:/var/www/magento
      - ./config/composer/auth.json:/var/www/.composer/auth.json
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
      - redis-obj
      - redis-ses
    env_file:
      - .env
  mysql:
    image: percona:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-log:/var/log/mysql
      - mysql-lib:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  redis-obj:
    image: redis:5
    restart: always
    ports:
      - "6379:6379"
  redis-ses:
    image: redis:5
    restart: always
    ports:
      - "6380:6380"
volumes:
  mysql-log:
  mysql-lib:
