version: '3'
services:
  nginx:
    build:
      args:
        nginx_port: 80
      context: ./docker/nginx
    depends_on:
      - php-fpm
    image: nginx:1.15
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./src/magento:/var/www/magento:cached
  php-fpm:
    build: ./docker/php-fpm
    env_file:
      - .env
    depends_on:
      - cron
      - elasticsearch
      - mysql
      - rabbitmq
      - redis-fpc
      - redis-obj
      - redis-ses
    restart: always
    volumes:
      - ./src/magento:/var/www/magento:cached
      - ./config/composer/auth.json:/var/www/.composer/auth.json:cached
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:cached
  cron:
    build: ./docker/cron
    restart: always
    volumes:
      - ./src/magento:/var/www/magento:cached
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    image: percona:5.7
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-log:/var/log/mysql
      - mysql-lib:/var/lib/mysql
  redis-obj:
    image: redis:5
    ports:
      - "6379:6379"
    restart: always
  redis-fpc:
    command: redis-server /usr/local/etc/redis/redis.conf
    image: redis:5
    ports:
      - "6380:6380"
    restart: always
    volumes:
      - ./config/redis/fpc.conf:/usr/local/etc/redis/redis.conf
  redis-ses:
    command: redis-server /usr/local/etc/redis/redis.conf
    image: redis:5
    ports:
      - "6381:6381"
    restart: always
    volumes:
      - ./config/redis/ses.conf:/usr/local/etc/redis/redis.conf
  elasticsearch:
    image: elasticsearch:6.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
volumes:
  mysql-log:
  mysql-lib:
